Doc update
kivy/kivy pull request #7342
Opened 2021-01-23 10:52 UTC by andresbrocco

Maintainer merge checklist
* [ ] Title is descriptive/clear for inclusion in release notes.
* [ ] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [ ] Applied the `release-highlight` label to be highlighted in release notes.
* [ ] Added to the milestone version it was merged into.
* [ ] **Unittests** are included in PR.
* [ ] Properly documented, including `versionadded`, `versionchanged` as needed.

2021-01-23 11:25 UTC, andresbrocco commented
@matham , could you check if I did anything wrong? Why did the build fail? My changes were minimal

2021-01-23 18:04 UTC, matham requested changes
You can ignore the failure. It happens sometimes and I'm not sure why.

2021-01-23 18:04 UTC, matham commented on kivy/uix/tabbedpanel.py
> +        for detailed usage.
```suggestion

        :meth:`switch_to` cannot be called from within the
        :class:`TabbedPanel` or its subclass' ``__init__`` method.
        If that is required, use the ``Clock`` to schedule it. See `discussion
        <https://github.com/kivy/kivy/issues/3493#issuecomment-121567969>`_
        for full example.
```

2021-01-24 09:45 UTC, matham approved these changes

2021-01-24 09:45 UTC, merged