Improve behavior of Widget.clear_widgets()
kivy/kivy pull request #7356
Opened 2021-02-01 06:32 UTC by pydsigner

Maintainer merge checklist
* [ ] Title is descriptive/clear for inclusion in release notes.
* [ ] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [ ] Applied the `release-highlight` label to be highlighted in release notes.
* [ ] Added to the milestone version it was merged into.
* [ ] **Unittests** are included in PR.
* [ ] Properly documented, including `versionadded`, `versionchanged` as needed.

2021-02-01 06:36 UTC, pydsigner commented
As noted in Discord discussion, this change *does* alter the API behavior, though not in a way that should break existing users.

2021-02-01 07:21 UTC, matham commented
Good catch about the possibility of someone passing in `children`.

Could you add unittests? You don't have to, but it would be nice if you added tests.

2021-02-02 00:37 UTC, pydsigner commented
> Good catch about the possibility of someone passing in `children`.

The case was being handled before, but not as well; if a list other than `children` was passed in, it would still be duplicated for no gain, and sequences other than lists (like iterators and sets) were being needlessly excluded.

> Could you add unittests? You don't have to, but it would be nice if you added tests.

Done.

2021-02-02 02:36 UTC, matham requested changes

2021-02-02 02:36 UTC, matham commented on kivy/tests/test_widget.py
> +
```suggestion

    def test_clear_widgets_children(self):
        root = self.root
        for _ in range(10):
            root.add_widget(self.cls())
        self.assertEqual(len(root.children), 10)

        root.clear_widgets(root.children)
        self.assertEqual(root.children, [])
```

To make sure passing in `children` works.

2021-02-02 05:21 UTC, matham approved these changes

2021-02-02 05:27 UTC, matham requested changes
Forgot to document changes.

2021-02-02 05:27 UTC, matham commented on kivy/uix/widget.py
>          '''
```suggestion
        .. versionchanged:: 2.1.0

            Specifying an empty ``children`` list leaves the widgets unchanged.
            Previously it was treated like ``None`` and all children were
            removed.
        '''
```

2021-02-02 05:55 UTC, matham approved these changes

2021-02-02 06:08 UTC, merged