enable pressure four touches in android (and ios?)
kivy/kivy pull request #7684
Opened 2021-11-12 00:03 UTC by tshirtman

Touch pressure on android worked back when we were using the pygame bootsrtap, but seem to have been lost since the switch to sdl2, this PR adds back the support using info from the SDL event.

Tested on two android devices, the value are very different from what we had with pygame, but seems more reasonable, so i updated the example rather than trying to mimic the previous range.

This shouldn't have any impact on desktop as we don't use the SDL events for touches there.
 
Maintainer merge checklist
* [ ] Title is descriptive/clear for inclusion in release notes.
* [ ] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [ ] Applied the `release-highlight` label to be highlighted in release notes.
* [ ] Added to the milestone version it was merged into.
* [ ] **Unittests** are included in PR.
* [ ] Properly documented, including `versionadded`, `versionchanged` as needed.

2021-11-12 20:01 UTC, misl6 commented
Will test it on iOS this weekend.

2021-11-13 11:10 UTC, misl6 requested changes

2021-12-11 14:47 UTC, tshirtman commented on examples/demo/touchtracer/main.py
>              if not .95 < (touch.pressure / ud['pressure']) < 1.05:
Update should avoid this issue.

2021-12-11 15:10 UTC, misl6 commented on examples/demo/touchtracer/main.py
>              if not .95 < (touch.pressure / ud['pressure']) < 1.05:
LGTM.

PEP8 is failing, can you take a look?

2021-12-21 19:48 UTC, misl6 approved these changes
LGTM!

2021-12-25 16:44 UTC, merged