iOS camera provider enhancements
kivy/kivy pull request #7857
Opened 2022-04-04 02:26 UTC by RobertFlatt

iOS camera provider enhancements, these are iOS only but implemented in the camera provider shared by iOS and MacOS.

The additional apis implement basic mobile camera functionality, this is not currently implemented.

To provide basic camera services on iOS, this PR adds
```
 def get_device_orientation(self):

 def change_camera_input(self, index):

 def zoom_level(self, level):

 def get_app_documents_directory(self):

 def save_texture(self, texture, filepath = '', quality = 0.9):
   # saves to iOS Photos App if filepath not specified,
   # or app documents directory if filepath is specified.
```

The fork also builds and runs on MacOS, indicating it is unlikely the changes have broken the MacOS camera provider.

TODO, but not part of this PR:

1) `kivy-ios` does not load the camera provider, the Camera widget fails. Assuming this PR is accepted in a timely fashion, I will implement `kivy-ios` PR that fixes the load and references this enhanced camera provider.

2) iOS has native photo and video capture apis, these are not currently implemented in this camera provider.

2022-04-05 02:56 UTC, RobertFlatt commented
~~kivy-ios does not load the camera provider, the Camera widget fails. Assuming this PR is accepted in a timely fashion, I will implement kivy-ios PR that fixes the load and references this enhanced camera provider.~~

Not required with kivy-ios master.

2022-04-07 20:19 UTC, misl6 reviewed
Code LGTM at a first glance!

I will test it on runtime (and will try to write a demo App, unless you already have one to share) during the upcoming weekend 😃

Super-minor: How about adding some logging when functionalities are not expected to be available but are called on macOS or vice-versa? Comments are super-fine, but users tend to not read them immediately. 😆

2022-04-07 21:45 UTC, RobertFlatt commented
This example uses the new features https://github.com/Android-for-Python/INDEX-of-Examples#c4k_photo_example

It depends on the Preview widget not the Camera widget. For iOS only, the **master** version of Preview is required https://github.com/Android-for-Python/Camera4Kivy . Release waits on this PR and a kivy-ios that points to the new Kivy master. 

The readme has not been updated for ios. Example shows switch between  cameras, capture photo or screenshot, pinch-spread for zoom (on my SE only the back camera), device rotation behavior, mirrored front camera. 

To enable use of the Camera 
```
        <key>NSCameraUsageDescription</key>
	<string> </string>
```
To enable save to Photos App
```
	<key>NSPhotoLibraryAddUsageDescription</key>
	<string> </string>
```
To make contents of local storage visible to File Manager
```
	<key>UIFileSharingEnabled</key>
	<true/>
        <key>LSSupportsOpeningDocumentsInPlace</key>
	<true/>
```
Image saves default to Photos App. The Preview widget storage selection is the same as for Android, so to save to app storage in place of Photos App  `capture_photo(location = 'private')` https://github.com/Android-for-Python/Camera4Kivy#location

[I started this because I wanted to try to port the tflite recipe, but my test example used a camera, so ...]

2022-04-09 16:16 UTC, misl6 requested changes
Tested it on my iPhone 12 Pro, and generally works good!

Unfortunately, after some minor edits to your example and `Camera4Kivy`, I wasn't able to attach the ultra-wide or telephoto (back) lenses due to how camera selection is handled.

I've added some comments explaining what could be done to improve it.

2022-04-09 16:16 UTC, misl6 commented on kivy/core/camera/camera_avfoundation_implem.m
> +    }
The new  [discoverySessionWithDeviceTypes:mediaType:position:](https://developer.apple.com/documentation/avfoundation/avcapturedevicediscoverysession/2361539-discoverysessionwithdevicetypes) allows a fairly more granular selection of the camera. 

The `devices` array may be not consistent of returning the "correct" order of the cameras, so could be nice to create an enumerator on Kivy side, and pass the configuration requested from the user to  `discoverySessionWithDeviceTypes:mediaType:position:`

2022-04-10 02:31 UTC, RobertFlatt commented
1) The api mentioned depends on ios10+ , (last time I looked) we build with minimum  9 not 10. And this is not adjustable https://github.com/kivy/kivy-ios/issues/691 On the subject of min api, the photo capture api gets good with ios11.

2) I don't understand enough about deviceTypes https://developer.apple.com/documentation/avfoundation/avcapturedevicetype or Apple devices  to implement this. It is not clear to me what the options do, or any side effects. 
I expect it is possible to synthesize some useful abstraction that extends Kivy's camera = [0,1] but at this point I don't know what it should be, or even what the usage model would be. So I would not try. 

3) This PR provides basic iOS functionality, which we don't have without the PR. We already know the camera provider could be improved, see the TODO at the top of the file. Support for ultrawide and telephoto should be added to that list.  Approve this PR as a starting point. Anybody who understands the additional enhancement design issues can then jump in.

2022-04-10 09:00 UTC, misl6 commented
1) Yeah, the API mentioned depends on iOS 10+, and we're still targeting iOS 9 minimum. (Maybe is a good idea to higher that requirement?). But, considering that on iOS is always a good practice to check for the availability of APIs (or for the iOS version that introduced that feature), we can easily switch between the two implementations during runtime.

2) Decrypting Apple's docs is always a nightmare, so not your fault 😄 

3) I agree that this PR is an improvement to the current situation, and will merge it as-is if you don't expect to continue working on it in the near/mid-term. In that case, I will open an issue that we'll need to likely target before releasing `2.2.x` regarding the deprecated code and missing support for non-standard cameras

2022-04-11 01:39 UTC, RobertFlatt commented
Updated the comments at the top.
I have other priorities so this is as far as I will take it. 
In the future maybe further enhancements will pop to the top of my stack.

2022-04-20 06:16 UTC, RobertFlatt commented
@misl6 Can you approve this, please.

2022-04-20 17:16 UTC, misl6 approved these changes
LGTM. Thank you!
I will open a couple of issues targeting what we discussed during the review.

2022-04-20 17:17 UTC, merged

2022-04-21 02:16 UTC, RobertFlatt commented
@misl6 You open to a kivy-ios PR that bumps the kivy version to include this change?

https://github.com/RobertFlatt/kivy-ios/blob/master/kivy_ios/recipes/kivy/__init__.py#L10

2022-04-23 07:45 UTC, misl6 commented
> LGTM. Thank you!
> I will open a couple of issues targeting what we discussed during the review.

See:
https://github.com/kivy/kivy/issues/7871