Detect High DPI on Linux Desktop
kivy/kivy pull request #8147
Opened 2023-02-26 22:38 UTC by jotoft

Maintainer merge checklist
* [ ] Title is descriptive/clear for inclusion in release notes.
* [ ] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [ ] Applied the `release-highlight` label to be highlighted in release notes.
* [ ] Added to the milestone version it was merged into.
* [ ] **Unittests** are included in PR.
* [ ] Properly documented, including `versionadded`, `versionchanged` as needed.

# Before patch on Linux with high DPI
Scaling is not working unless setting the DPI and density manually using the environment variables `KIVY_DPI` and `KIVY_METRICS_DENSITY`.
![image](https://user-images.githubusercontent.com/5873750/221440994-d1a04357-1c32-497c-8667-e3c41e56b838.png)

# After patch on Linux with high DPI
DPI is correctly set to the same as X11 is configured to.
![image](https://user-images.githubusercontent.com/5873750/221441034-47408b0d-fecc-4f40-8fed-c7047e1bdc91.png)

## Implementation
The DPI can be found using this SDL function [SDL_GetDisplayDPI](https://wiki.libsdl.org/SDL2/SDL_GetDisplayDPI). 

The warning suggests using another method, which is the one already used in `kivy/core/window/window_sdl2.py`
This other method I think only really works for macOS and IOS with retina displays.

So, if we are on a desktop and this method fails, then try to get the DPI using the SDL function and if that does not work we use the default of 96. Which will yield a density of 1.0 when density is calculated on Linux (with 74b866d9e53859d832519840637d28a42e82d429) as well as the other desktop OSes.

2023-03-06 17:20 UTC, akshayaurora requested changes

2023-03-06 17:21 UTC, akshayaurora commented
@jotoft everything seems to work as expected. Just that there is not automatic change when the UI has a change in DPI at run time. Which I gather you were not after. If you would please make the changes requested in the review.

2023-03-06 20:13 UTC, jotoft commented on kivy/tools/precommit_hooks/pre-commit-config.yaml
> +-   repo: https://github.com/pycqa/flake8
Dropped this part from this PR now. Will check on the unit test failure.

2023-03-06 20:27 UTC, jotoft commented
Made the unit test tolerate a bit higher difference, that was what failed:

Changed the tolerance to 1E-2 instead. They pass at 1E-3 here but realistically it is not really important that they have to be this accurate, and would rather be a bit lenient here to avoid confusion.

```
 FAILED kivy/tests/test_properties.py::test_numeric_string_with_units_check[True] - AssertionError: 9903.6552734375 != 9903.655700683594 within 1e-05 delta (0.00042724609375 difference)
FAILED kivy/tests/test_properties.py::test_numeric_string_with_units_check[False] - AssertionError: 9903.6552734375 != 9903.655700683594 within 1e-05 delta (0.00042724609375 difference)
= 2 failed, 848 passed, 22 skipped, 1 xfailed, 1 warning in 213.37s (0:03:33) ==
Error: Process completed with exit code 1.
```

2023-03-10 09:46 UTC, akshayaurora approved these changes

2023-03-10 11:48 UTC, merged