Fixing `TypeError` on `parse_level` method from Parser
kivy/kivy pull request #8206
Opened 2023-04-13 02:52 UTC by FilipeMarch

When you are write something like this:
```yml
BoxLayout:
    orientation: 'vertical'
        Button:
```
You would get this error:
```
  File "/.venv/lib/python3.10/site-packages/kivy/lang/parser.py", line 756, in parse_level
    if current_property[:3] == "on_":
TypeError: 'NoneType' object is not subscriptable
```
Because `current_property` is None, and on [line 756](https://github.com/kivy/kivy/blob/master/kivy/lang/parser.py#L756) we try to subscript it. But this error is not informative and does not allow the developer to know where the error comes from. In this case we should show in which line there is a invalid declaration,  by raising a `ParserException`.

After the changes, this is the result:
```
kivy.lang.parser.ParserException: Parser: File "main.kv", line 3:
...
    1: BoxLayout:
    2:     orientation: 'vertical'
>>  3:        Button:
    4:
    5:
...
Invalid declaration
```

Maintainer merge checklist
* [x] Title is descriptive/clear for inclusion in release notes.
* [ ] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [ ] Applied the `release-highlight` label to be highlighted in release notes.
* [ ] Added to the milestone version it was merged into.
* [ ] **Unittests** are included in PR.
* [ ] Properly documented, including `versionadded`, `versionchanged` as needed.

2023-06-18 14:22 UTC, misl6 reviewed
Hi @FilipeMarch !

Nice, small, and clean!
Sorry for the late reply, but we were into the `2.2.x` release process.

How do you feel about adding a test that exercises this issue?

2023-10-29 15:16 UTC, misl6 commented
Ping @FilipeMarch

2023-10-29 23:39 UTC, FilipeMarch commented
I'm sorry for this long time without answering you. I will add a test.

2023-11-24 08:26 UTC, FilipeMarch commented
I'm catching an extra indentation declaration; added two tests, one for each case. @misl6

2023-11-24 16:58 UTC, misl6 requested changes
Hi @FilipeMarch !

The PEP8 check is failing, can you please take care of it?

Feel free to ping me when you're ready for another review!

2023-11-25 06:55 UTC, FilipeMarch commented
> Hi @FilipeMarch !
> 
> The PEP8 check is failing, can you please take care of it?
> 
> Feel free to ping me when you're ready for another review!

@misl6 Done!

2023-11-25 09:04 UTC, misl6 approved these changes
LGTM. Thank you!

2023-11-25 09:08 UTC, merged