Remove all the PY2 compat code
kivy/kivy pull request #8610
Opened 2024-02-11 20:31 UTC by Valinor

See #8566

* [X] Title is descriptive/clear for inclusion in release notes.
* [ ] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [ ] Applied the `release-highlight` label to be highlighted in release notes.
* [ ] Added to the milestone version it was merged into.
* [ ] **Unittests** are included in PR.
* [ ] Properly documented, including `versionadded`, `versionchanged` as needed.

2024-02-14 19:39 UTC, misl6 requested changes
Hi @Valinor !

I've left some minor suggestions.

Nice work and cleanup 🧹 BTW!

2024-02-14 19:39 UTC, misl6 commented on kivy/tests/test_fbo_py2py3.py
Maybe we can rename the whole test file and rename `FBOPy2Py3TestCase` (if it makes sense to have this test) ?

2024-02-14 19:39 UTC, misl6 commented on kivy/uix/rst.py
>              self._parser.parse(text, document)
Maybe:
```
self._parser.parse(self.text, document)
```

2024-02-15 07:09 UTC, Valinor commented
> Hi @Valinor !
> 
> I've left some minor suggestions.
> 
> Nice work and cleanup 🧹 BTW!

Thanks for the review. Shame on me to let pass all of these :').

I will try to understand why some tests fails on the ci, and not for me, and take care of your suggestions.

2024-02-17 14:06 UTC, misl6 commented
> I will try to understand why some tests fails on the ci

When you push changes, make sure to rebase on top of latest master, as the CI errors you seen might be related to https://github.com/kivy/kivy/pull/8618 (so, not your fault)

2024-02-22 17:04 UTC, misl6 commented
@Valinor FYI:

We also may want to do some cleanup here:
https://github.com/kivy/kivy/blob/dc7fd3d8ae28029ebecfbb923af37caa4a5245c9/kivy/uix/screenmanager.py#L1090

2024-03-02 08:26 UTC, misl6 commented
Hi @Valinor,

This is a friendly ping, are you still active on this PR?

2024-03-23 16:25 UTC, misl6 commented
@Valinor FYI: I've performed some changes to your PR due to inactivity, thank you for doing most of the work BTW!

2024-03-23 16:25 UTC, merged

2024-03-23 16:56 UTC, Valinor commented
> @Valinor FYI: I've performed some changes to your PR due to inactivity, thank you for doing most of the work BTW!

Thanks, and sorry for my inactivity. I will try to be more productive next time. Great change, thanks for your work.

2024-08-29 12:09 UTC, Samael-TLB commented
@misl6 
A question on your pr [Avoid trickery for next iterator](https://github.com/kivy/kivy/pull/8610/commits/b77587c9a1999fad4f90d76fdbda2911044d1595)

Why have we removed the api function to cleanly get the next screen from the screenmanager? As per current implementation, people will need to do next(sm) and not sm.next(), which feels a bit unintuitive in lieu of class based apis. Am I missing anything, can you help me understand the reason?