Remove deprecated style keyword
kivy/kivy pull request #8709
Opened 2024-04-28 22:09 UTC by kbaikov

Fixes: 8230

Style keyword is deprecated in sphinx 7.x

Maintainer merge checklist
* [ ] Title is descriptive/clear for inclusion in release notes.
* [ ] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [ ] Applied the `release-highlight` label to be highlighted in release notes.
* [ ] Added to the milestone version it was merged into.
* [ ] **Unittests** are included in PR.
* [ ] Properly documented, including `versionadded`, `versionchanged` as needed.

2024-04-29 16:35 UTC, misl6 requested changes
Hi @kbaikov ,

That's nice that you started working on an open issue (https://github.com/kivy/kivy/issues/8230) for Kivy 3.0.0, however I do not think that's the proper way to target this issue.

Can you please explain your changes?

2024-04-30 19:11 UTC, kbaikov commented
Hi @misl6 

Thank you for a quick reply.
So my thinking was to install sphinx version 7.x and try to build kivy documentation with a simple make target.
`make html` or `make -C doc html`
This is the minimal fix that makes the docs to build.

Perhaps i am missing something else. Please direct me.
Thanks!

2024-05-02 11:04 UTC, kbaikov commented
@misl6 
Indeed, thank you.
Please take a look at the latest change.
This builds in the latest sphinx and leaves the HTML tag alone.

2024-05-02 16:41 UTC, misl6 requested changes

2024-05-02 18:16 UTC, kbaikov commented
Fixed a typo.

2024-05-02 18:16 UTC, kbaikov commented on doc/sources/.templates/layout.html
> +    {%- for style in syles %}
Fixed

2024-05-04 08:41 UTC, misl6 approved these changes
LGTM. Thank you!

2024-05-04 08:41 UTC, merged