Add `triggered_method`
kivy/kivy pull request #8915
Opened 2024-11-09 06:19 UTC by clayote

An analogue to the existing `@triggered` decorator, for when you want to decorate a method, like on a `Widget`.

It's technically a class, but I'm using snake_case for it because you still use it like any other decorator.

Maintainer merge checklist
* [ ] Title is descriptive/clear for inclusion in release notes.
* [ ] Applied a `Component: xxx` label.
* [ ] Applied the `api-deprecation` or `api-break` label.
* [ ] Applied the `release-highlight` label to be highlighted in release notes.
* [ ] Added to the milestone version it was merged into.
* [ ] **Unittests** are included in PR.
* [ ] Properly documented, including `versionadded`, `versionchanged` as needed.

2024-11-13 19:22 UTC, kengoon commented
@clayote did you put into consideration that `@triggered` accepts a delay argument?

2025-01-10 20:13 UTC, misl6 requested changes
Does not seem to work, is something missing in commits?
Can you please add a test to ensure that works and document it?


```
     @triggered
      ^^^^^^^^^
   File "/Users/mirko/Documents/projects/kivy/kivy/clock.py", line 1149, in triggered
     return wrapper_triggered(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/Users/mirko/Documents/projects/kivy/kivy/clock.py", line 1128, in wrapper_triggered
     cb_trigger = Clock.create_trigger(
                  ^^^^^^^^^^^^^^^^^^^^^
   File "kivy/_clock.pyx", line 378, in kivy._clock.CyClockBase.create_trigger
     cpdef ClockEvent create_trigger(
   File "kivy/_clock.pyx", line 421, in kivy._clock.CyClockBase.create_trigger
     cdef ClockEvent ev = ClockEvent(
   File "kivy/_clock.pyx", line 37, in kivy._clock.ClockEvent.__init__
     self, CyClockBase clock, int loop, callback, double timeout,
 TypeError: must be real number, not function
 ```

2025-01-26 04:20 UTC, clayote commented
Sorry about that. It works now, and I've included a test.

2025-03-13 06:46 UTC, akshayaurora approved these changes

2025-03-13 06:47 UTC, merged